#!/bin/sh

# Get OS info to determine package manager
if [ -e /etc/os-release ]; then
  . /etc/os-release;
fi
if [ "$ID" = "ubuntu" ] || [ "$ID" = "debian" ] || [ "$ID" = "linuxmint" ]; then
  vimCmd="vim"
elif [ "$ID" = "fedora" ] || [ "$ID" = "rhel" ] || [ "$ID" = "rocky" ]; then
  vimCmd="vimx"
else
  echo "Untested OS. Please verify and improve this script."
  exit 1
fi

serv=${S:-xtvim}

if $vimCmd --serverlist | grep -qxiF "$serv"; then
  $vimCmd --servername "$serv" --remote-tab "$@"
else
  xterm -name "$serv" -e vim -p --servername "$serv" "$@" &
fi
